name: Setup Node.js Project
description: Configures Node.js, fetches dependencies, and manages caching.

inputs:
    node-version:
        required: true
        description: Node.js version to set up

runs:
    using: "composite"
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@v4
          with:
              version: 8.15.9

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: "pnpm"

        - name: Install dependencies
          shell: bash
          run: pnpm install
          env:
              PUPPETEER_SKIP_DOWNLOAD: true

        - name: Setup chrome binary cache
          uses: actions/cache@v3
          with:
              path: ~/.cache/puppeteer/
              key: ${{ runner.os }}-chrome-${{ hashFiles('packages/ui-components/node_modules/puppeteer-core/src/revisions.ts') }}-${{ hashFiles('packages/ui-components/node_modules/puppeteer/src/node/install.ts') }}

        - name: Download chrome binary
          shell: bash
          working-directory: packages/ui-components/node_modules/puppeteer
          run: pnpm postinstall
