name: ci

on:
    pull_request:
        branches:
            - dev
            - master

jobs:
    ci:
        strategy:
            matrix:
                os: [ubuntu-22.04]
                node: [22.x]

        name: Continuous Integration (${{ matrix.os }} / Node.js ${{ matrix.node }})
        runs-on: ${{ matrix.os }}

        steps:
            - name: ☁️ Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 🟩 Setup Node.js ${{ matrix.node }}
              uses: ./.github/actions/node-setup
              with:
                  node-version: ${{ matrix.node }}

            - name: 🔍 Run linter
              run: pnpm lint

            - name: 🧪 Run tests
              run: pnpm test

            - name: 🏗️ Build all packages
              run: pnpm build:packages

            - name: 💅 Build storybook
              run: pnpm storybook:build
