name: ci

on:
    pull_request:
        branches:
            - dev
            - master

jobs:
    ci:
        strategy:
            matrix:
                os: [ubuntu-22.04]
                node: [18.x]

        name: Continuous Integration (${{ matrix.os }} / Node.js ${{ matrix.node }})
        runs-on: ${{ matrix.os }}

        steps:
            - name: ☁️ Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 🟩 Setup Node.js ${{ matrix.node }}
              uses: ./.github/actions/node-setup
              with:
                  node-version: ${{ matrix.node }}

            - name: 🐉 Bootstrap repository
              run: npm run bootstrap

            - name: 🔍 Run linter
              run: npm run lint

            - name: 🧪 Run tests
              run: npm run test

            - name: 🏗️ Build all packages
              run: npm run build:packages

            - name: 💅 Build storybook
              run: npm run storybook:build
