name: publish-dev

on:
    push:
        branches:
            - dev

permissions:
    contents: write # for checkout and tag

jobs:
    publish:
        strategy:
            matrix:
                os: [ubuntu-22.04]
                node: [22.x]

        name: Publish Storybook (${{ matrix.os }} / Node.js ${{ matrix.node }})
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.RELEASE_TOKEN }}

            - name: Setup Node.js ${{ matrix.node }}
              uses: ./.github/actions/node-setup
              with:
                  node-version: ${{ matrix.node }}
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build:packages
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish Alpha & Master Storybook to GitHub Pages
              run: |
                  git switch -f master
                  npm run bootstrap
                  npm run build:packages
                  npm run storybook:deploy -- -- -- --out='./gp' --dry-run
                  git switch -f dev
                  npm run bootstrap
                  npm run build:packages
                  npm run storybook:deploy -- -- -- --out='./gp/alpha' --dry-run
                  npm run storybook:deploy -- -- -- --existing-output-dir='./gp'
              env:
                  GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
