name: publish-master
on:
    push:
        branches:
            - master

permissions:
    contents: write # for checkout and tag

jobs:
    publish:
        strategy:
            matrix:
                os: [ubuntu-22.04]
                node: [18.x]

        name: Publish Master (${{ matrix.os }} / Node.js ${{ matrix.node }})
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.RELEASE_TOKEN }}

            - name: Git Identity
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Authenticate with Registry
              run: |
                  echo "registry=http://registry.npmjs.org/" > .npmrc
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
                  npm whoami
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Setup Node.js ${{ matrix.node }}
              uses: ./.github/actions/node-setup
              with:
                  node-version: ${{ matrix.node }}
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Bootstrap
              run: npm run bootstrap
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Generate Versions
              run: npx lerna version --yes --conventional-commits --no-changelog --no-git-tag-version --no-push --force-publish=*
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build
              run: npm run build:packages
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish to NPM JS
              run: |
                  git reset --hard
                  npx lerna publish --no-verify-access --yes --force-publish=*
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish Alpha & Master Storybook to GitHub Pages
              run: |
                  npm run storybook:deploy -- -- -- --out='./gp' --dry-run
                  git switch -f dev
                  npm run bootstrap
                  npm run build:packages
                  npm run storybook:deploy -- -- -- --out='./gp/alpha' --dry-run
                  npm run storybook:deploy -- -- -- --existing-output-dir='./gp'
              env:
                  GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
